services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=
      - NEXTAUTH_SECRET=
      - KEYCLOAK_CLIENT_ID=
      - KEYCLOAK_CLIENT_SECRET=
      - KEYCLOAK_ISSUER=
      - GOOGLE_API_KEY=
      - GOOGLE_CLIENT_EMAIL=
      - GOOGLE_ADMIN_SID=
      - GOOGLE_ADMIN_HSID=
      - GOOGLE_ADMIN_SSID=
      - GOOGLE_ADMIN_APISID=
      - GOOGLE_ADMIN_SAPISID=
      - GOOGLE_ADMIN_SAPISID_HASH=
      - GOOGLE_ADMIN_AUTHUSER=
      - IPA_SERVER_URL=
      - IPA_SERVER_COOKIE=